[package]
name = "sphira_defi"
edition = "2024.beta"
version = "1.0.0"

[dependencies]
One = { git = "https://github.com/one-chain-labs/onechain.git", subdir = "crates/sui-framework/packages/one-framework", rev = "main" }

[addresses]
sphira_defi = "0x0"

[dev-dependencies]

[dev-addresses]
